package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;
import java.util.List;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {      // class  fille       implements = classe abstraite       quand interface
                                                                              // extends
    private List<User> users = generateUsers();     // normalement ajouter des utilisateus


    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override   // vérifie que la méthode est correctement utilise de la classe parent
    public List<User> getUsers() {  // obtenir un utilisateur             Fonction

        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {  //   générer des utilisateurs aléatoires
        users.add(User.random());
    }          // add

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {   // supprimer un utilisateur

        users.remove(user);
    }  // remove
}
